# Generated by Django 5.2.10 on 2026-01-07 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_detections', models.PositiveIntegerField(default=1)),
                ('face_roi', models.ImageField(blank=True, null=True, upload_to='attendance_faces/')),
                ('recognized_emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(default='undefined', max_length=10)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('parish_pastor', 'Parish Pastor'), ('department_head', 'Department Head'), ('ushering_head_admin', 'Ushering Head Admin'), ('usher_admin', 'Usher Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_detections', models.PositiveIntegerField(default=1)),
                ('face_roi', models.ImageField(blank=True, null=True, upload_to='temp_attendance_faces/')),
                ('recognized_emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(default='undefined', max_length=10)),
                ('role', models.CharField(default='visitor', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
