# Generated by Django 5.2.10 on 2026-01-07 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendanceapi', '0002_initial'),
        ('base', '0001_initial'),
        ('userauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_embedding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tempattendance',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department'),
        ),
        migrations.AddField(
            model_name='tempattendance',
            name='temp_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.tempuser'),
        ),
    ]
