# Generated by Django 5.2.10 on 2026-01-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='appearances',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
